Update BillingTemplateClientAddSubscriber.php
CHIPAsia/chip-php-sdk pull request #12
Opened 2023-11-19 18:09 UTC by MSufianS

**Issue**
Fixes #11 

**Description**
This pull request resolves the following issue:
`"Class "\Chip\Model\Billing\Purchase" does not exist"`

**Testing**
 Tested the fix locally and verified that the error no longer occurs.

2023-12-11 05:30 UTC, wzul requested changes
Changing from @var without the use of @var means ignoring the type hinting.

So, instead of removing type hinting, it is best to correct the namespace for Purchase.

Good catch!

2023-12-11 05:30 UTC, wzul commented on lib/Model/Billing/BillingTemplateClientAddSubscriber.php
> +  #BillingTemplateClient
Kindly revert back this change

2023-12-11 05:30 UTC, wzul commented on lib/Model/Billing/BillingTemplateClientAddSubscriber.php
> +  #Purchase
Kindly change this to:

```php
/**
 *
 * @var \Chip\Model\Purchase
 */
```

2023-12-12 04:11 UTC, MSufianS reviewed
Tested.. Working well...

2023-12-12 04:37 UTC, wzul approved these changes

2023-12-12 04:43 UTC, merged